---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "next"]

jobs:
  release:
    name: Create Release
    uses: kilip/gh-common/.github/workflows/ansible-release.yml@wip
    secrets: inherit
    permissions:
      contents: write
    with:
      release_branches: main
