---
name: Release

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Testing"]
    branches: ["1.0", "next"]
    types:
      - completed

jobs:
  release:
    name: Create Release
    uses: kilip/gh-common/.github/workflows/ansible-release.yml@wip
    secrets: inherit
    permissions:
      contents: write
