---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["next"]

jobs:
  release:
    name: Create Release
    uses: kilip/gh-common/.github/workflows/ansible-release.yml@wip
    secrets: inherit
    permissions:
      contents: write
