---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["1.x"]

jobs:
  release:
    name: Create Release
    uses: kilip/gh-common/.github/workflows/ansible-release.yml@main
    secrets: inherit
    permissions:
      contents: write
    with:
      release_branches: main,1.x
