---
name: Release

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Testing"]
    branches: ["next"]
    types:
      - completed

jobs:
  release:
    name: Create Release
    uses: kilip/gh-common/.github/workflows/ansible-release.yml@main
    secrets: inherit
    permissions:
      contents: write
    with:
      release_branches: next
