---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - next
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"
      - ".github/renovate/**.json5"
      - ".github/workflows/renovate.yaml"

{%- raw %}
jobs:
  renovate:
    name: Renovate
    uses: kilip/gh-common/.github/workflows/run-renovate.yaml@main
    with:
      configurationFile: ".github/renovate.json5"
      dryRun: "${{ inputs.dryRun || 'false' }}"
      renovateLogLevel: "${{ inputs.logLevel || 'debug' }}"
    secrets:
      app_id: "${{ secrets.BOT_APP_ID }}"
      app_private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
{% endraw %}
