---
name: Testing

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "1.0"]

jobs:
  testing:
    uses: kilip/gh-common/.github/workflows/ansible-testing.yml@main
    with:
      dists: ubuntu-22.04
