---
name: Testing

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip

      - name: Install test dependencies.
        run:
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install cookiecutter

      - name: Create cookie cutter project
        run:
          cookiecutter --config-file .github/test-config.yml gh:kilip/molecule-cookiecutter

      - name: Run molecule testing
        working-directory: test
        run:
          molecule test
